// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9y9l5C8AaPpMAToV2YINwEA9qKqinkGM',
    appId: '1:1086607525009:web:bebe94a4c16dd2b1536b30',
    messagingSenderId: '1086607525009',
    projectId: 'eduxions',
    authDomain: 'eduxions.firebaseapp.com',
    storageBucket: 'eduxions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMoogYOQzbFhoyN7XvKhBdX62zeVdweSc',
    appId: '1:1086607525009:android:4b1d52cc035288a8536b30',
    messagingSenderId: '1086607525009',
    projectId: 'eduxions',
    storageBucket: 'eduxions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAMKaeR53dYWFNOR_8MzSHMYgEADnCtKk',
    appId: '1:1086607525009:ios:641b2400bd4510fe536b30',
    messagingSenderId: '1086607525009',
    projectId: 'eduxions',
    storageBucket: 'eduxions.firebasestorage.app',
    iosBundleId: 'com.example.edux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAMKaeR53dYWFNOR_8MzSHMYgEADnCtKk',
    appId: '1:1086607525009:ios:641b2400bd4510fe536b30',
    messagingSenderId: '1086607525009',
    projectId: 'eduxions',
    storageBucket: 'eduxions.firebasestorage.app',
    iosBundleId: 'com.example.edux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9y9l5C8AaPpMAToV2YINwEA9qKqinkGM',
    appId: '1:1086607525009:web:48d4105b1785323d536b30',
    messagingSenderId: '1086607525009',
    projectId: 'eduxions',
    authDomain: 'eduxions.firebaseapp.com',
    storageBucket: 'eduxions.firebasestorage.app',
  );
}
